name: runs-on FreeBSD
run-name: ${{ inputs.runs-on }}
on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true
      steps:
        type: string
        required: true
jobs:
  freebsd:
    name: ""
    runs-on: macos-12
    steps:
      - run: echo "$JSON"
        env: { JSON: "${{ toJSON(github) }}" }
      - name: "ðŸŒŸ MAIN"
        run: true # curl -fsSL https://raw.githubusercontent.com/runs-on/freebsd/main/main.sh | bash
